// Pokemons Constants

export const GET_POKEMONS_STARTS = "GET_POKEMONS_STARTS";

export const GET_POKEMONS = "GET_POKEMONS";
export const GET_ONE_POKEMON = "GET_ONE_POKEMON";

export const GET_POKEMONS_DONE = "GET_POKEMONS_DONE";
export const GET_POKEMONS_FAILED = "GET_POKEMONS_FAILED";

export const GET_ONE_POKEMON_DONE = "GET_POKEMONS_ONE_DONE";
export const GET_ONE_POKEMON_FAILED = "GET_POKEMONS_ONE_FAILED";
